@import gg.jte.Content
@param Content content

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Welcome page</title>
    <title>/courses</title>
    <title>/</title>
</head>
<body>
<p>
    <a href="/">Main</a>
    <a href="/courses">Courses</a>
</p>
<p>COURSES:
</p>
${content}
<footer style="color: red; font-size: 10px;">
    <br>
    <hr>
    Курсы
</footer>
</body>
</html>